(source gnu)
(source melpa)

(depends-on "better-defaults")
(depends-on "cask")
(depends-on "cider")
(depends-on "dash")
(depends-on "epl")
(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "magit")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "zenburn-theme")
